gui-title: "&6%player_name%'s Stats"
gui-size: 45

items:
  crop-stats:
    material: PLAYER_HEAD
    skull: "%player_name%" # uses player's head
    slot: 10
    name: "&a%player_name%'s Crop Stats"
    glow: true
    lore:
      - "&eCarrots Broken: &f%statistic_mine_block:carrots%"
      - "&ePotatoes Broken: &f%statistic_mine_block:potatoes%"
      - "&eSugar Cane Broken: &f%statistic_mine_block:sugar_cane%"

  mob-stats:
    material: NETHER_STAR
    slot: 12
    name: "&c%player_name%'s Mob Stats"
    glow: false
    lore:
      - "&eDragons Killed: &f%statistic_kill_entity:ender_dragon%"
      - "&eWithers Killed: &f%statistic_kill_entity:wither%"

  backgroud:
    material: GRAY_STAINED_GLASS_PANE
    slot: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 31, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44 ]
    name: " "
    glow: false
    lore:
      - "&7I am useless"